### ISSUE TITLE
Defekte Tests

### ISSUE THREAD

**Issue by JohannesHoppe** [MichaelKaaden/book-monkey#2]
'n Abend! Die Tests sind meine Baustelle.
Und du hast natürlich absolut recht, geht so nicht. Wir müssen dem Leser zeigen, wie sie wieder grün werden.

Kannst du mir bitte bestätigen,

1. das du den kompletten BM fertig hast
2. dass du bislang noch nichts an den automatisch generierten Tests verändert hast?

Wenn ich jetzt also deine roten Tests fixe, dann wäre alles perfekt - oder? :smile:

**Comment by MichaelKaaden** [comment]
Der BM ist durch. Ich habe nur die Versorgung von Konstruktoren angepasst, sofern diese Argumente erwarteten, etwa bei der DelayDirective, und die von Euch im Buch vorgegebenen Änderungen.

**Comment by JohannesHoppe** [comment]
Das wird wieder eine Nachtschicht! :laughing:

**Comment by MichaelKaaden** [comment]
Da gibt's nur zwei Alternativen zu: Entweder den Test als "out of scope" für das Buch kennzeichnen oder aber weniger auf die Meinung der freiwilligen Fachkorrektur hören. Ansonsten musst Du da leider durch. :-)

Übrigens bin ich die letzten drei Wochen auch fast jeden Abend am Buch gesessen. ;-)

**Comment by JohannesHoppe** [comment]
Da werde ich dann mal durch! Dein Einsatz ist wirklich genial! 😊

**Comment by MichaelKaaden** [comment]
Tapfer! 👍 

Hört sich an, als bekäme ein Exemplar des Buches, wenn ihr durch seid. 😉

**Comment by JohannesHoppe** [comment]
Ich muss den Verlag fragen, ob er ein Exemplar mit goldenem Einband produziert! ;-)

**Comment by MichaelKaaden** [comment]
Du meinst, ich sollte aufhören, damit ihr kein schlechtes Gewissen haben müsst? 😂 Nee, da müsst ihr jetzt schon durch.

**Comment by JohannesHoppe** [comment]
Haben wir nicht mehr hinein bekommen. Wäre womöglich auch ein wenig langweilig geworden! ;-)

Jetzt steht im Buch folgendes:

![image](https://cloud.githubusercontent.com/assets/640639/22303912/a33b17ea-e335-11e6-8c20-fc14f4ca800d.png)
